CREATE DATABASE CUSTOMER_BEHAVIOR;
SHOW DATABASES;
USE CUSTOMER_BEHAVIOR;

-- Q1. HOW MUCH REVENUE COMES FROM MALE & FEMALE CUSTOMERS ?
SELECT
    GENDER,
    SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVERAGE_PURCHASE
FROM CUSTOMER
GROUP BY GENDER
ORDER BY TOTAL_REVENUE DESC;


-- Q2. WHICH CUSTOMERS USED A DISCOUNT BUT SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT?
SELECT CUSTOMER_ID , PURCHASE_AMOUNT FROM CUSTOMER
WHERE DISCOUNT_APPLIED = 'YES'
AND PURCHASE_AMOUNT >= (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER );


-- Q3. WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING ?
SELECT ITEM_PURCHASED , ROUND(AVG(REVIEW_RATING),2) AS 'AVERAGE PRODUCT RATING' FROM CUSTOMER 
GROUP BY ITEM_PURCHASED
ORDER BY AVG (REVIEW_RATING) DESC
LIMIT 5;


-- Q4. COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING. 
SELECT SHIPPING_TYPE, ROUND(AVG(PURCHASE_AMOUNT),2) FROM CUSTOMER 
WHERE SHIPPING_TYPE IN ('STANDARD' , 'EXPRESS')
GROUP BY SHIPPING_TYPE;


-- Q5. DO SUBSCRIBED CUSTOMERS SPEND MORE ? COMPARE AVERAGE SPEND TOTAL REVENUE BETWEEN SUBSCRIBERS & NON SUBSCRIBERS.
SELECT SUBSCRIPTION_STATUS , COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS , ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVERAGE_SPEND , ROUND(SUM(PURCHASE_AMOUNT), 2) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS
ORDER BY AVERAGE_SPEND DESC;


-- Q6. WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED ?
SELECT ITEM_PURCHASED , ROUND(100 * SUM(CASE WHEN DISCOUNT_APPLIED = 'YES' THEN 1 ELSE 0 END) / COUNT(*),2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;


-- Q7. SEGMENT CUSTOMERS INTO NEW , RETURNING, AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASE , AND SHOW THE COUNT OF EACH SEGMENT. 
WITH CUSTOMER_TYPE AS (SELECT CUSTOMER_ID , PREVIOUS_PURCHASES , CASE
WHEN PREVIOUS_PURCHASES = 1 THEN 'NEW'
WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'RETURNING'
ELSE 'LOYAL'
END AS CUSTOMER_SEGMENT
FROM CUSTOMER )
SELECT CUSTOMER_SEGMENT , COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_CUSTOMERS DESC;


-- Q8. WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY ?
WITH ITEM_COUNTS AS ( SELECT CATEGORY , ITEM_PURCHASED , COUNT(CUSTOMER_ID) AS TOTAL_ORDERS, ROW_NUMBER() OVER (PARTITION BY CATEGORY 
ORDER BY COUNT(CUSTOMER_ID) DESC) 
AS ITEM_RANK
FROM CUSTOMER
GROUP BY CATEGORY, ITEM_PURCHASED )

SELECT CATEGORY , ITEM_RANK , ITEM_PURCHASED , TOTAL_ORDERS FROM ITEM_COUNTS
WHERE ITEM_RANK <= 3
ORDER BY CATEGORY, ITEM_RANK;


-- Q9. ARE CUSTOMERS WHO ARE REPEAT BUYERS ( MORE THAN 5 PREVIOUS PURCHASES ) ALSO LIKELY TO SUBSCRIBE ?
SELECT SUBSCRIPTION_STATUS , COUNT(CUSTOMER_ID) AS REPEAT_BUYERS , ROUND(100 * COUNT(CUSTOMER_ID) / (SELECT COUNT(CUSTOMER_ID) FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5),2) AS PERCENTAGE_OF_REPEAT_BUYERS FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS
ORDER BY PERCENTAGE_OF_REPEAT_BUYERS DESC;


-- Q10. WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP ?
SELECT AGE_GROUP , ROUND(SUM(PURCHASE_AMOUNT), 2) AS TOTAL_REVENUE , ROUND(100 * SUM(PURCHASE_AMOUNT) / (SELECT SUM(PURCHASE_AMOUNT) 
FROM CUSTOMER),2) AS REVENUE_CONTRIBUTION_PERCENT FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY REVENUE_CONTRIBUTION_PERCENT DESC;


